### ISSUE TITLE
[DESIGN] Input

### ISSUE THREAD

**Issue by yangareum1818** [woongteco/nextcamp-12t#7]
### type
- input 태그의 type 값 중 사용되는 유형
  - text, number, email, passowrd, search, 댓글 textarea
  - 기본 input 디자인 대신 아이콘으로 대체: checkbox/checkbox-button, radio/radio-button
- 라이브러리를 사용한 유형
  - text rich editor, date-range picker, select&multi-select

### usage
next.js에서 input 요소는 단독으로 사용되기 보다 form 내부에서 form action을 통해 데이터를 백엔드로 전달하기 때문에 label 요소, 혹은 다른 input 요소와 합쳐져 사용됩니다.

**Comment by callmebyneon** [comment]
### form input field
- [x] big desktop(xl)에서는 3:9 칼럼의 그리드 레이아웃
- [x] xl 이하에서는 flex-col 레이아웃

### usage  - 예시 #27 

```tsx
// src/app/(route)/post/write/page.tsx #27 
function () {
  ...
  return (
    ...
    <Field>
      <LabelText form required>
        글 제목
      </LabelText>
      <Input.Text placeholder="제목을 입력하세요" required />
    </Field>
    ...
  )
}
```
